sudo: required
dist: trusty
language: java
before_install:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "$SSH_KEY" > ~/.ssh/id_rsa.pub
  - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa*
  - eval `ssh-agent -s`
  - cat ~/.ssh/id_rsa.pub
  - cat ~/.ssh/id_rsa
script:
    - sh ci.sh
notifications:
    email: false
